language: dart
sudo: true

dart:
  - dev

dart_task:
  - test: -j 1
    xvfb: false
  - dartanalyzer
  - dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
